taniab_hw11
aodarc/LIST-010 pull request #25
Opened 2018-12-24 09:07 UTC by undef1nd

@aodarc, Please, review.

2019-01-04 19:36 UTC, undef1nd commented
@aodarc just a kindly reminder :-)

2019-01-14 15:02 UTC, aodarc requested changes

2019-02-03 16:12 UTC, undef1nd commented on homework/taniab/tania_hw_11.py
> +Write a python program that takes a list of file extensions and prints all the files from the current directory matching the extension given.
Fixed.

2019-02-03 16:12 UTC, undef1nd commented on homework/taniab/tania_hw_11.py
> +    return cfg['ext_mappings']
Fixed. Please, take a look once again.

2019-02-05 14:39 UTC, aodarc approved these changes

2019-02-05 14:39 UTC, merged